global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'feature_processor'
    static_configs:
      - targets: ['feature-processor:8081']
    metrics_path: '/metrics'

  - job_name: 'spark_metrics'
    static_configs:
      - targets: ['feature-processor:8082']
    metrics_path: '/metrics/prometheus'
