FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-asyncio httpx

COPY . .

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/app

CMD ["pytest", "-v", "app/tests"]
